version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: library-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
    volumes:
      - db_data:/var/lib/mysql
      - ./library.sql:/docker-entrypoint-initdb.d/library.sql:ro
    ports:
      - "3306:3306"

  app:
    build: ./LibraryProject2
    container_name: library-java-app
    depends_on:
      - mysql
    environment:
      DB_HOST: jdbc:mysql://mysql:3306/library
      DB_USER: root
      DB_PASS: root
    ports:
      - "5000:5000"

volumes:
  db_data:
