apiVersion: v1
kind: Service
metadata:
  name: library-app-service
spec:
  type: ClusterIP
  ports:
    - port: 5000          # ðŸ‘ˆ changed from 8080
      targetPort: 5000    # ðŸ‘ˆ changed from 8080
  selector:
    app: library-app
